CUDA_VISIBLE_DEVICES=5 python main.py \
--cg_tau 0.01 \
--n_parties=10 \
--use_project_head 0 \
--lam_fm 50.0 \
--start_ep_fm 20 \
--dataset=cifar100 \
--device cuda:2 \
--model=resnet50 \
--alg=fedfm \
--lr=0.01 \
--epochs=10 \
--comm_round=100 \
--partition=noniid \
--beta=0.5 \
--print_local_test_acc 0 \
--logdir='./logs/' \
--datadir='/GPFS/data/ruiye/fssl/dataset/cifar100'