CUDA_VISIBLE_DEVICES=3 python main.py \
--cg_tau 0.1 \
--lam_fm 50.0 \
--start_ep_fm 20 \
--use_project_head 0 \
--fm_avg_anchor 0 \
--dataset=cifar10 \
--device cuda:2 \
--model=resnet18_7 \
--alg=fedfm \
--lr=0.01 \
--epochs=10 \
--comm_round=100 \
--n_parties=10 \
--partition=noniid \
--beta=0.5 \
--logdir='./logs/' \
--datadir='/GPFS/data/ruiye/fssl/dataset'